//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budgee_Setup_Custom.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Budgee_Setup_Custom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE [master]
        ///
        ///IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = &apos;Budgee&apos;)
        ///BEGIN
        ///	CREATE DATABASE [Budgee]
        ///END
        ///GO.
        /// </summary>
        internal static string install_part1 {
            get {
                return ResourceManager.GetString("install_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE [Budgee]
        ///GO
        ////****** Object:  Table [dbo].[Caracteristica]    Script Date: 12/2/2022 14:55:20 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[Caracteristica](
        ///	[ID_Caracteristica] [uniqueidentifier] NOT NULL,
        ///	[Nombre] [varchar](50) NOT NULL,
        ///	[Color] [varchar](50) NULL,
        ///	[ID_Usuario] [uniqueidentifier] NOT NULL,
        ///	[Estado] [bit] NOT NULL,
        ///	[Tipo_Caracteristica] [varchar](50) NOT NULL,
        /// CONSTRAINT [PK_Etiqueta] PRIMARY KEY CLUSTERED 
        ///(
        ///	[ID_Caracteristica] ASC        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string install_part2 {
            get {
                return ResourceManager.GetString("install_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE [master]
        ///GO
        ///IF EXISTS(SELECT * FROM sys.databases WHERE name = &apos;Budgee&apos;)
        ///BEGIN
        ///	EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N&apos;Budgee&apos;
        ///	ALTER DATABASE [Budgee] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
        ///	ALTER DATABASE [Budgee] SET  SINGLE_USER
        ///	DROP DATABASE [Budgee]
        ///END
        ///GO.
        /// </summary>
        internal static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
    }
}
