//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lapso
    {
        public System.Guid ID_Lapso { get; set; }
        public string Tipo_Lapso { get; set; }
        public Nullable<System.DateTime> Fecha_Desde { get; set; }
        public Nullable<System.DateTime> Fecha_Hasta { get; set; }
        public System.Guid ID_Usuario { get; set; }
    }
}
