//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.SesionTrack = new HashSet<SesionTrack>();
            this.Usuario_Familia = new HashSet<Usuario_Familia>();
            this.Usuario_Patente = new HashSet<Usuario_Patente>();
        }
    
        public System.Guid ID_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Password_Usuario { get; set; }
        public bool Estado { get; set; }
        public byte[] timestamp { get; set; }
        public System.Guid ID_Configuracion_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionTrack> SesionTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Familia> Usuario_Familia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Patente> Usuario_Patente { get; set; }
        public virtual Configuracion_Usuario Configuracion_Usuario { get; set; }
    }
}
