//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planificacion_Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planificacion_Transaccion()
        {
            this.PlanificacionTransaccion_Etiqueta = new HashSet<PlanificacionTransaccion_Etiqueta>();
            this.Variable = new HashSet<Variable>();
        }
    
        public System.Guid ID_Planificacion_Transaccion { get; set; }
        public string Descripcion_Planificacion { get; set; }
        public string Descripcion_Transaccion { get; set; }
        public Nullable<System.Guid> ID_Categoria { get; set; }
        public string Tipo_Operacion { get; set; }
        public System.Guid ID_Monto_Expresion { get; set; }
        public System.Guid ID_FrecuenciaInicio { get; set; }
        public Nullable<System.Guid> ID_RecordatorioLigado { get; set; }
        public bool Quitar_Al_Concluir { get; set; }
        public bool Habilitado { get; set; }
        public System.Guid ID_Cuenta { get; set; }
        public bool Estado { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Expresion Expresion { get; set; }
        public virtual Recordatorio Recordatorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanificacionTransaccion_Etiqueta> PlanificacionTransaccion_Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variable { get; set; }
    }
}
