//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recordatorio()
        {
            this.Notificacion = new HashSet<Notificacion>();
            this.Planificacion_Transaccion = new HashSet<Planificacion_Transaccion>();
        }
    
        public System.Guid ID_Recordatorio { get; set; }
        public string Descripcion { get; set; }
        public System.Guid ID_FrecuenciaInicio { get; set; }
        public bool Establecer_Notif_Windows { get; set; }
        public bool Establecer_Alarma_Windows { get; set; }
        public bool Quitar_Al_Concluir { get; set; }
        public bool Habilitado { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planificacion_Transaccion> Planificacion_Transaccion { get; set; }
    }
}
