//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgeeSLEntities : DbContext
    {
        public BudgeeSLEntities()
            : base("name=BudgeeSLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<Familia_Familia> Familia_Familia { get; set; }
        public virtual DbSet<Familia_Patente> Familia_Patente { get; set; }
        public virtual DbSet<Patente> Patente { get; set; }
        public virtual DbSet<Usuario_Familia> Usuario_Familia { get; set; }
        public virtual DbSet<Usuario_Patente> Usuario_Patente { get; set; }
        public virtual DbSet<SesionTrack> SesionTrack { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Configuracion_Usuario> Configuracion_Usuario { get; set; }
        public virtual DbSet<Lapso> Lapso { get; set; }
        public virtual DbSet<FrecuenciaInicio> FrecuenciaInicio { get; set; }
    }
}
