//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuracion_Usuario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public System.Guid ID_Configuracion_Usuario { get; set; }
        public string Divisa_Default { get; set; }
        public string Idioma { get; set; }
        public bool Mantener_Sesion_Iniciada { get; set; }
        public bool Alarmas_Windows { get; set; }
        public bool Notificaciones_Windows { get; set; }
        public bool Notificaciones_Presupuestos { get; set; }
        public bool Notificaciones_Recordatorios { get; set; }
        public bool Notificaciones_Estadisticas { get; set; }
        public bool Notificaciones_Expiran { get; set; }
        public string Notificaciones_Expiran_Frecuencia { get; set; }
        public Nullable<int> Notificaciones_Expiran_Valor { get; set; }
        public bool Respaldar { get; set; }
        public bool Limite_Respaldos { get; set; }
        public Nullable<int> Respaldos_Cantidad_Maxima { get; set; }
        public Nullable<System.Guid> ID_FrecuenciaInicio_Respaldos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual FrecuenciaInicio FrecuenciaInicio { get; set; }
    }
}
