//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia_Familia
    {
        public System.Guid ID_Familia_Padre { get; set; }
        public System.Guid ID_Familia_Hija { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual Familia Familia { get; set; }
        public virtual Familia Familia1 { get; set; }
    }
}
