//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrecuenciaInicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FrecuenciaInicio()
        {
            this.Configuracion_Usuario = new HashSet<Configuracion_Usuario>();
        }
    
        public System.Guid ID_FrecuenciaInicio { get; set; }
        public string FrecuenciaMagnitud { get; set; }
        public Nullable<int> FrecuenciaValor { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Dia_del_Mes { get; set; }
        public string Dia_de_la_Semana { get; set; }
        public System.TimeSpan Horario { get; set; }
        public Nullable<System.DateTime> Fecha_Ultimo_Proceso { get; set; }
        public System.Guid ID_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuracion_Usuario> Configuracion_Usuario { get; set; }
    }
}
