//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionTrack
    {
        public System.Guid ID_SesionTrack { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public System.DateTime Fecha_Proceso { get; set; }
        public byte[] TimeStamp { get; set; }
        public string TipoTrack { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
