//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgeeEntities : DbContext
    {
        public BudgeeEntities()
            : base("name=BudgeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Expresion> Expresion { get; set; }
        public virtual DbSet<Expresion_Variable> Expresion_Variable { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<PlanificacionTransaccion_Etiqueta> PlanificacionTransaccion_Etiqueta { get; set; }
        public virtual DbSet<PlantillaTransaccion_Etiqueta> PlantillaTransaccion_Etiqueta { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Transaccion_Etiqueta> Transaccion_Etiqueta { get; set; }
        public virtual DbSet<Caracteristica> Caracteristica { get; set; }
        public virtual DbSet<Planificacion_Transaccion> Planificacion_Transaccion { get; set; }
        public virtual DbSet<Recordatorio> Recordatorio { get; set; }
        public virtual DbSet<Plantilla_Transaccion> Plantilla_Transaccion { get; set; }
        public virtual DbSet<Presupuesto> Presupuesto { get; set; }
        public virtual DbSet<Variable> Variable { get; set; }
    }
}
