//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caracteristica()
        {
            this.PlanificacionTransaccion_Etiqueta = new HashSet<PlanificacionTransaccion_Etiqueta>();
            this.PlantillaTransaccion_Etiqueta = new HashSet<PlantillaTransaccion_Etiqueta>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Transaccion_Etiqueta = new HashSet<Transaccion_Etiqueta>();
            this.Planificacion_Transaccion = new HashSet<Planificacion_Transaccion>();
            this.Plantilla_Transaccion = new HashSet<Plantilla_Transaccion>();
            this.Variable = new HashSet<Variable>();
            this.Variable1 = new HashSet<Variable>();
        }
    
        public System.Guid ID_Caracteristica { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public bool Estado { get; set; }
        public string Tipo_Caracteristica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanificacionTransaccion_Etiqueta> PlanificacionTransaccion_Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillaTransaccion_Etiqueta> PlantillaTransaccion_Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Etiqueta> Transaccion_Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planificacion_Transaccion> Planificacion_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla_Transaccion> Plantilla_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variable1 { get; set; }
    }
}
