//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expresion_Variable
    {
        public System.Guid ID_Expresion { get; set; }
        public System.Guid ID_Variable { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual Expresion Expresion { get; set; }
        public virtual Variable Variable { get; set; }
    }
}
