//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public System.Guid ID_Notificacion { get; set; }
        public string Informacion { get; set; }
        public string Procedencia { get; set; }
        public Nullable<System.Guid> ID_Recordatorio { get; set; }
        public Nullable<System.Guid> ID_Presupuesto { get; set; }
        public string Tipo_Estadistica { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public bool Visto { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Recordatorio Recordatorio { get; set; }
        public virtual Presupuesto Presupuesto { get; set; }
    }
}
