//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla_Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantilla_Transaccion()
        {
            this.PlantillaTransaccion_Etiqueta = new HashSet<PlantillaTransaccion_Etiqueta>();
            this.Variable = new HashSet<Variable>();
        }
    
        public System.Guid ID_Plantilla_Transaccion { get; set; }
        public string Descripcion_Plantilla { get; set; }
        public string Descripcion_Transaccion { get; set; }
        public Nullable<System.Guid> ID_Categoria { get; set; }
        public string Tipo_Operacion { get; set; }
        public Nullable<System.Guid> ID_Monto_Expresion { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual Expresion Expresion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillaTransaccion_Etiqueta> PlantillaTransaccion_Etiqueta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variable { get; set; }
    }
}
