//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuesto()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public System.Guid ID_Presupuesto { get; set; }
        public string Descripcion { get; set; }
        public string Cuando_Chequear { get; set; }
        public System.Guid ID_Variable_Supervisada { get; set; }
        public string Operador_Relacional { get; set; }
        public System.Guid ID_Condicion_Expresion { get; set; }
        public Nullable<System.Guid> ID_Lapso_Frecuencia { get; set; }
        public bool Establecer_Notif_Windows { get; set; }
        public bool Establecer_Alarma_Windows { get; set; }
        public bool Habilitado { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Expresion Expresion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual Variable Variable { get; set; }
    }
}
