//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion_Etiqueta
    {
        public System.Guid ID_Transaccion { get; set; }
        public System.Guid ID_Etiqueta { get; set; }
        public int Orden { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Caracteristica Caracteristica { get; set; }
    }
}
