//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Transaccion_Etiqueta = new HashSet<Transaccion_Etiqueta>();
            this.Variable = new HashSet<Variable>();
        }
    
        public System.Guid ID_Transaccion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> ID_Categoria { get; set; }
        public string Tipo_Operacion { get; set; }
        public System.Guid ID_Monto_Expresion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Concretada { get; set; }
        public System.Guid ID_Cuenta { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Expresion Expresion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Etiqueta> Transaccion_Etiqueta { get; set; }
        public virtual Caracteristica Caracteristica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variable { get; set; }
    }
}
