//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Repositories.SqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variable()
        {
            this.Expresion_Variable = new HashSet<Expresion_Variable>();
            this.Presupuesto = new HashSet<Presupuesto>();
        }
    
        public System.Guid ID_Variable { get; set; }
        public string Nombre_Variable { get; set; }
        public string Tipo_Variable { get; set; }
        public Nullable<System.Guid> ID_Categoria { get; set; }
        public Nullable<System.Guid> ID_Etiqueta { get; set; }
        public Nullable<System.Guid> ID_Cuenta { get; set; }
        public Nullable<System.Guid> ID_Transaccion { get; set; }
        public Nullable<System.Guid> ID_Planificacion_Transaccion { get; set; }
        public Nullable<System.Guid> ID_Plantilla_Transaccion { get; set; }
        public Nullable<System.Guid> ID_Lapso { get; set; }
        public System.Guid ID_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual Caracteristica Caracteristica1 { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expresion_Variable> Expresion_Variable { get; set; }
        public virtual Planificacion_Transaccion Planificacion_Transaccion { get; set; }
        public virtual Plantilla_Transaccion Plantilla_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuesto> Presupuesto { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
